name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install pytest pytest-mock flake8

    - name: Run flake8
      run: PYTHONPATH=$PYTHONPATH:$(pwd) flake8 stockguard/ tests/ --ignore=W292,W293,E302

    - name: Run pytest
      run: PYTHONPATH=$PYTHONPATH:$(pwd) python -m pytest -v